### ISSUE TITLE
[Feature] Match Skill Level 

### ISSUE THREAD

**Issue by kshammer** [yasp-dota/parser#59]
Currently on a players page in the match list each match is listed as having an unknown skill. 
![image](https://user-images.githubusercontent.com/5688067/174741368-4115bdd0-f6f9-4b7b-bcc6-651589e3c5f0.png)

After reviewing the web repo I don't believe this is a bug. It appears that the field is never populated with any data. I checked the clarity protobuf repo and found something that looked promising called AverageSkill. After extracting the value on a few replays I believe the field is dead as the value is always 0. 
![image](https://user-images.githubusercontent.com/5688067/174741986-839499cd-f49b-4a2d-a587-e7060ba2130f.png)
![image](https://user-images.githubusercontent.com/5688067/174742294-41bbe6b8-67b6-464a-90b6-be71c2024bca.png)

I checked dotabuff and iirc they used to have a skill rating associated with every match and now it looks like they are using average rank. 
![image](https://user-images.githubusercontent.com/5688067/174742578-1a635dfd-c0e8-46e6-b26c-73273b005637.png)

After trying to figure out which protobuf value they are using to pull the average rank I came up blank and was hoping someone else would have an idea on what to do. I think this is a cool stat to have and I would like to have it visible on opendota.

**Comment by builder-247** [comment]
They have probably deprecated the field, it really is just a relic from before ranked matchmaking even existed that uses hardcoded mmr ranges.

**Comment by howardchung** [comment]
Skill data is no longer available--we should remove it from the UI (and maybe replace with the average medal rank)
